# Generated by Django 6.0.1 on 2026-01-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('city', models.CharField(default='Chennai', max_length=100)),
                ('hospital', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
